- name: install docker-ce repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker-ce
  # latest stable versions as of 4/19/24
  package:
    name:
      - docker-ce-3:27.5.1-1.el9
      - docker-ce-cli-1:27.5.5-1.el9
      - containerd.io-1.6.31-3.1.el9
      - python3-docker

- set_fact:
    docker_compose_command: "docker compose"
