- name: install docker-ce repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker-ce
  # latest stable versions as of 4/19/24
  package:
    name:
      - docker-ce-3:26.0.2-1.el9
      - docker-ce-cli-1:26.0.2-1.el9
      - containerd.io-1.6.31-3.1.el9
      - docker-buildx-plugin-0.14.0-1.el9
      - docker-compose-plugin-2.26.1-1.el9
      - python-requests
      - python3-docker

- set_fact:
    docker_compose_command: "docker compose"