- name: install docker-ce repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: uninstall older versions of docker from original installs
  package:
    name:
      - docker-ce-3:26.0.2-1.el9
      - docker-ce-cli-1:26.0.2-1.el9
      - containerd.io-1.6.31-3.1.el9
      - docker-buildx-plugin-0.14.0-1.el9
      - docker-compose-plugin-2.26.1-1.el9
      - python3-requests
    state: absent

- name: install docker-ce
  # latest stable versions as of 3/7/25
  # installing docker-ce installs the appropriate dependencies that were previously defined here:
  # - docker-ce-cli, containerd-io, docker-buildx-plugin, docker-compose-plugin
  package:
    name:
      # let docker-ce determine the corresponding packages it requires
      - docker-ce-3:28.0.1-1.el9