- name: git ssh key
  copy:
    dest: "{{git_key_file_prefix}}{{item.name}}"
    content: "{{item.private_key}}"
    mode: 0600
  diff: no


- name: ssh command for git
  copy:
    dest: "{{git_ssh_prefix}}{{item.name}}"
    mode: 0744
    content: |
      #!/bin/sh
      ssh -i {{git_key_file_prefix}}{{item.name}} -o IdentitiesOnly=yes "$@"
