- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart chronyd
  service:
    name: chronyd
    state: restarted

- name: reconfigure squid
  command: docker exec {{compose_project_name}}_squid_1 squid -k reconfigure

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: restart squid v2
  community.docker.docker_compose_v2:
    state: restarted
    project_src: "{{compose_project_dir}}"
    services:
      - squid

- name: restart ingrid v2
  community.docker.docker_compose_v2:
    state: restarted
    project_src: "{{compose_project_dir}}"
    services:
      - ingrid
