#!/bin/bash -eu
#
# This script is used to run the ansible-galaxy iridl installation.
# It will check for the existence of the virtual environment: /opt/datalib_venv3.12
#
VENV=/opt/datalib_venv3.12
BUILD=""
BECOME="--ask-become-pass"

function showhelp()
{
    echo "$0 [--build] [ansible-playbook arguments]"
    echo " --build:                   Optional argument to build or rebuild the classic maprooms."
    echo "                            This can take a long time."
    echo "ansible-playbook arguments: Optional arguments that will be passed to the ansible-playbook, such as"
    echo "                            --check and/or -v"
    echo ""
    exit
}

function show_venv_error()
{
        echo ""
        echo "Couldn't activate Python environment ${VENV}"
        echo "Please review the installation documentation: https://dldocs.iri.columbia.edu/admin/"
        echo ""
        exit 1

}
while (( $# )); do
    case $1 in
        --build)
          BUILD="-e run_update_script=yes"
          shift
          ;;
        --nopw)
          BECOME="--become"
          shift
          ;;
        -h* | --h*)
          showhelp
          ;;
        *)
          break
          ;;
    esac
done

# Check if the virtual environment exists
echo -n "checking python virtual environment..."
if [ -d "${VENV}" ]; then
    if ! source "${VENV}/bin/activate"; then
        show_venv_error
    fi
else
    show_venv_error
fi
echo "ok"

# check for secrets.yaml file
if [ ! -f "../secrets.yaml" ]; then
    echo "../secrets.yaml file doesn't exist.  Please review the documentation regarding deploy keys:"
    echo "* https://dldocs.iri.columbia.edu/admin/"
    echo ""
    exit 1
fi

echo "ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${BUILD} playbook.yaml $*"
ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${BUILD} playbook.yaml $*