#!/usr/bin/env bash
#
# This script is used to run the ansible-galaxy iridl installation.
# It will check for the existence of the virtual environment: /opt/datalib_venv3.12
#
# It will check for any local git changes that might need to be pushed, and it will check for
# any git changes that need to be pulled.
##
VENV=/opt/datalib_venv3.12
BUILD=""
CHECK=""
VERBOSE=""
BECOME="--ask-become-pass"

function showhelp()
{
  echo "$0 [--build] [--check] [-v]"
  echo " --check:     Optional argument to check what will be done without making changes."
  echo " --build:     Optional argument to build or rebuild the maprooms.  This can take a long time."
  echo " -v:          Optional argument to make the output more verbose.  Use multiple times to increase verbose-ness (i.e. -vv)"
  echo ""
  exit
}

while (( $# )); do
  case $1 in
    --build)
      BUILD="-e run_update_script=yes"
      ;;
    --check)
      CHECK="--check"
      ;;
    --nopw)
      BECOME="--become"
      ;;
    -v*)
      ;;
    *)
      showhelp
      ;;
  esac
  shift
done

# Check if the virtual environment exists
echo -n "checking python virtual environment..."
if [ -d "${VENV}" ]; then
  if ! source "${VENV}/bin/activate"; then
    echo ""
    echo "Couldn't activate Python environment ${VENV}"
    echo "Please review the documentation: https://dldocs.iri.columbia.edu/admin/server/centos9_stream.html#install_python"
    exit 1
  fi
fi
echo "ok"

# check for secrets.yaml file
if [ ! -f "../secrets.yaml" ]; then
  echo "../secrets.yaml file doesn't exist.  Please read the documentation on deploy keys and Configuring your Data Library:"
  echo "* https://dldocs.iri.columbia.edu/admin/git.html#deployment-keys"
  echo "* https://dldocs.iri.columbia.edu/admin/installation.html#configure-your-data-library-repository"
  echo ""
  exit 1
fi

echo "ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${CHECK} ${BUILD} ${VERBOSE} playbook.yaml"
ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${CHECK} ${BUILD} ${VERBOSE} playbook.yaml