namespace: iridl
name: iridl
version: 0.0.0

readme: README.md
authors:
  - IRI Data Library Team <help@iri.columbia.edu>
description: Tools for installing and maintaining a server that runs the IRI Data Library software
license: MIT

repository: https://github.com/iridl/iridl-ansible

build_ignore:
  - test-inventory-iri.yaml
  - test-inventory.yaml
  - test-secrets.yaml
  - test.yaml
  - Vagrantfile
  - .vagrant*
