- hosts: dlservers
  vars_files:
    - test-secrets.yaml
  vars:
    # Path of the directory where datasets are stored. This is
    # typically a volume with multiple TB of space, and ideally
    # not the root volume.
    data_dir: "/data1/datalib/data"

    # Path of the directory where the docker daemon's data will
    # go, including volumes and container images. This can take up
    # tens of GB, so it's best not to put it on the root
    # volume. We typically put it on the same volume as data_dir
    # (see above).
    docker_dir: "/data1/docker"

    # See defaults/main.yaml
    docker_registry_mirror: http://10.0.2.2:5000

    dl_hostport: localhost:8090

    # SMTP relay host:port in postfix format,
    # e.g. [mail-relay.iri.columbia.edu]:25
    mail_relay:

    # Email address that users of your Data Library should write
    # to for help
    support_email:

    # Email address to which automated messages about system
    # status will be sent
    admin_emails: []

    # Replace with the URLs of your country-specific dlentries and
    # maproom repositories. Here we are using anonymous access
    # over HTTPS, but if your repositories require authentication,
    # configure the access key in the secrets file and specify the
    # repositories like this:
    #
    #    dlentries_repo: git@bitbucket.org:iridl/dlentries_mycountry.git
    #    maproom_repo: git@bitbucket.org:iridl/maproom_mycountry.git
    dlentries_repo: https://bitbucket.org/iridl/dlentries_testcountry.git
    maproom_repo: https://bitbucket.org/iridl/maproom_testcountry.git

    # Container version numbers for the various Data Library software
    # packages. Do not use "latest", or you might find your software
    # being updated when you don't expect it, potentially to a
    # non-backwards-compatible version
    ingrid_version: d250324
    ingriddb_version: 1322790
    maproom_base_version: ce2f974
    maproom_dev_version: ce2f974
    dlsquid_version: e16cb8b

  roles:
    - iridl
