# -*- mode: ruby -*-
# vi: set ft=ruby :

$bootstrap= <<-EOF
#!/bin/bash
set -e
sed -i s/SELINUX=enforcing/SELINUX=permissive/ /etc/selinux/config 
setenforce permissive
dnf install -y git python3.12
python3.12 -m venv /opt/datalib_venv3.12
/opt/datalib_venv3.12/bin/pip install --upgrade pip
/opt/datalib_venv3.12/bin/pip install ansible==11.3.0 requests==2.32.3
EOF

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  resizedisk = <<-SCRIPT
        source /etc/os-release
        # CentOS Stream 10 uses partition 2 for the disk, but 9 uses partition 1
        if [ ${VERSION_ID} == "10" ]; then
            PARTITION=2
        elif [ ${VERSION_ID} == "9" ]; then
            PARTITION=1
        else
            exit -1
        fi

        # expand the partition to its max size, which has been defined
        # in the vm config x.vm.disk.
        echo ", +" | sfdisk -f -N ${PARTITION} /dev/sda
        partprobe
        resize2fs -F /dev/sda${PARTITION}
        shutdown -r now
  SCRIPT

  config.vm.define "dlserver1", primary: true do |x|
    x.vm.box = "centos/stream10"
    x.vm.disk :disk, size: '20GB', primary: true
    x.vm.box_check_update = false
    x.vm.network "forwarded_port", guest: 22, host: 2230 # must match ansible_port in inventory
    x.vm.network "forwarded_port", guest: 80, host: 8090 # must match test_port in inventory
    x.vm.provider :virtualbox do |vb|
      vb.memory = 5 * 1024
    end
    x.vm.synced_folder "..", "/vagrant"
    x.vm.provision "shell", :inline => $bootstrap
    x.vm.provision "shell", :inline => resizedisk
  end

end
