- name: conda environment lockfile from url
  get_url:
    url: "{{conda_env_url}}"
    dest: "{{conda_envs_dir}}/{{conda_env_name}}-conda-linux-64.lock"
  when: conda_env_url is defined

- name: conda environment lockfile from local file
  copy:
    src: "{{conda_env_file}}"
    dest: "{{conda_envs_dir}}/{{conda_env_name}}-conda-linux-64.lock"
  when: conda_env_file is defined

- name: conda environment {{conda_env_name}}
  shell: ". {{miniconda_path}}/etc/profile.d/conda.sh && conda create -n {{conda_env_name}} --file {{conda_envs_dir}}/{{conda_env_name}}-conda-linux-64.lock"
  args:
    creates: "{{miniconda_path}}/envs/{{conda_env_name}}/bin/python"
