#!/usr/bin/env bash

export GIT_SSH=/usr/local/bin/ssh-git

fail() {
    echo $2 >&2
    exit $1
}

init_git() {
    local repo=$1
    local target=$2
    local version=$3

    mkdir -p $target
    if [ ! -d $target/.git ]; then
        git clone --recursive $repo $target || fail $? "git clone failed"
    fi

    cd $target || fail "failed to cd to target dir $target"

    git fetch origin $version || fail $? "git fetch failed"
    git checkout -- . || fail $? "git checkout -- . failed"
    git -c advice.detachedHead=false checkout FETCH_HEAD || \
        fail $? "failed to checkout version $version"
    git submodule update --init --recursive || fail $? "failed to update submodules"

}

if [[ $(id -u) != 0 ]]; then
    fail 1 "This script should be run with sudo."
fi


### dlentries

if [[ ! -z "{{dlentries_repo}}" ]]; then
    init_git {{dlentries_repo}} {{dlentries_dir}} {{dlentries_version}}
fi

### maproom

init_git {{maproom_repo}} {{maproom_src_dir}} {{maproom_version}}

# cleanup beforehand
git clean -fdx || fail $? "git clean failed"
git submodule foreach --recursive git clean -fdx || fail $? "submodule clean failed"

if [[ -t 1 ]]; then  # if running in an interactive terminal
    interactive_args=-it
fi

docker run --rm $interactive_args --user 0 \
       -v $PWD:/build/maproom iridl/maproom-dev:{{maproom_dev_version}} \
       ./build.sh utbuild.tag || fail $? "maproom build failed"

mkdir -p {{maproom_install_dir}} || fail $? "couldn't create install dir"
cp -r ___build/* {{maproom_install_dir}} || fail $? "failed to install maprooms"

# seemingly necessary to get updates to show up (at least immediately)
if [[ -d {{compose_project_dir}} ]]; then  # doesn't exist yet on first run
    cd {{compose_project_dir}} || fail $? "failed to cd"
    docker-compose restart ingrid
    docker-compose restart maproom
fi

exit 0
