#!/usr/bin/env bash

fail() {
    local status=$1
    # don't accidentally return success code
    if [[ $((status)) -eq 0 ]]; then
        status=1
    fi
    echo $2 >&2
    exit $status
}

init_git() {
    local repo=$1
    local target=$2
    local version=$3
    export GIT_SSH=$4

    # Check if $target is a valid clone of the right repo. If not, remove it.
    if [[ -e $target ]]; then
        if remotes=$(cd $target && git remote -v); then
            # extract the remote url and compare it to $repo
            remote=$(echo "$remotes" | grep -P '^origin\t.*\(fetch\)$' | awk '{print $2}') || fail
            if [[ "$remote" != $repo ]]; then
                # remote has changed; remove so we can reclone
                rm -r $target || fail
            fi
        else
            # $target is not a valid git repo. Remove it and start fresh.
            rm -r $target || fail
        fi
    fi

    if [[ ! -e $target ]]; then
        git clone --recursive $repo $target || fail $? "git clone failed"
    fi

    cd $target || fail $? "failed to cd to target dir $target"

    git fetch origin $version || fail $? "git fetch failed"
    git checkout -- . || fail $? "git checkout -- . failed"
    git -c advice.detachedHead=false checkout FETCH_HEAD || \
        fail $? "failed to checkout version $version"
    git submodule update --init --recursive || fail $? "failed to update submodules"


    git clean -fdx || fail $? "git clean failed"
    git submodule foreach --recursive git clean -fdx || fail $? "submodule clean failed"
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --build-classic)
        build_classic=YES
        shift
        ;;
    *)
        fail 1 "Unknown argument '$1'"
        shift
        ;;
  esac
done

if [[ $(id -u) != 0 ]]; then
    fail 1 "This script should be run with sudo."
fi

# properly set interactive flags if in an interactive for any docker commands we run
if [[ -t 1 ]]; then
    interactive_args=-it
fi

### dlentries

{% if dlentries_repo is defined %}
    init_git {{dlentries_repo.url}} {{dlentries_dir}} {{dlentries_repo.version}} {{git_ssh_prefix}}{{dlentries_repo.name}}
{% endif %}

### python maproom

# only if we actually have a python maproom for this deployment
{% if python_maproom_repo is defined %}
init_git {{python_maproom_repo.url}} {{python_maproom_src_dir}} \
         {{python_maproom_repo.version}} {{git_ssh_prefix}}{{python_maproom_repo.name}}

docker build -t {{python_maproom_repo.name}}:{{python_maproom_repo.version}} . || fail $? "python maproom build failed"

cd {{python_maproom_src_dir}}/update || fail $? "python maproom repo does not have an update script"
docker build -t {{python_maproom_repo.name}}-update:{{python_maproom_repo.version}} . || fail $? "python maproom update container build failed"
{% endif %}

### maproom

init_git {{maproom_repo.url}} {{maproom_src_dir}} {{maproom_repo.version}} {{git_ssh_prefix}}{{maproom_repo.name}}

if [ ! -z "${build_classic}" ]; then
    docker run --rm $interactive_args --user 0 \
           -v $PWD:/build/maproom iridl/maproom-dev:{{maproom_dev_version}} \
           ./build.sh utbuild.tag || fail $? "maproom build failed"

    mkdir -p {{maproom_install_dir}} || fail $? "couldn't create install dir"
    cp -r ___build/* {{maproom_install_dir}} || fail $? "failed to install maprooms"
fi

# seemingly necessary to get updates to show up (at least immediately)
if [[ -d {{compose_project_dir}} ]]; then  # doesn't exist yet on first run
    cd {{compose_project_dir}} || fail $? "failed to cd"

    docker-compose up -d

    docker-compose restart ingrid
    docker-compose restart maproom
    # in case one of the services was previously down, tell squid to check again.
    docker-compose exec -T squid squid -k reconfigure
fi

exit 0
