#!/bin/bash

set -e

fcst_name=$1

configs_dir={{python_maproom_src_dir}}/pycpt-forecasts

config_dir="$configs_dir/$fcst_name"
if [ $# -ne 1 ] || ! [ -d "$config_dir" ]; then
    echo "Usage: $0 <forecast_name>"
    echo "forecast_name must match one of the subdirectories of $configs_dir :"
    ls "$configs_dir"
    exit 1
fi

# read pycpt version from config file
pycpt_version=$(cat "$config_dir/pycpt-version")

# activate conda environment for the specified pycpt version
source {{miniconda_path}}/etc/profile.d/conda.sh
conda activate pycpt-$pycpt_version

# run pycpt
upload-forecasts "$config_dir/config.py"
